packages:
  - list
  - store
  - injector
  - refine-partition
  - smart-mock
  - get-parameter-names
  - jsx
  - element

onlyBuiltDependencies:
  - esbuild
patchedDependencies:
  '@changesets/assemble-release-plan@6.0.9': patches/@changesets__assemble-release-plan@6.0.9.patch
