env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  space-before-blocks:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  no-trailing-spaces:
    - error
    - skipBlankLines: true
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always