name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@slimlib'
      - run: yarn
      - run: yarn workspaces run build
      - run: yarn workspaces run test
      - run: yarn workspaces run publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}